version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: {{CONTAINER_NAME}}
    restart: unless-stopped
    environment:
      PHP_VERSION: {{PHP_VERSION}}
      {{DB_ENVIRONMENT}}
      {{REDIS_ENVIRONMENT}}
    volumes:
      - ./app:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
    {{DATABASE_DEPENDS}}
    {{REDIS_DEPENDS}}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{CONTAINER_NAME}}.rule={{TRAEFIK_RULE}}"
      - "traefik.http.routers.{{CONTAINER_NAME}}.entrypoints={{ENTRYPOINTS}}"
      - "traefik.http.services.{{CONTAINER_NAME}}.loadbalancer.server.port=80"
      {{SSL_LABELS}}
    networks:
      - default

  {{DATABASE_SERVICE}}

  {{REDIS_SERVICE}}

{{VOLUMES}}

networks:
  default:
    external:
      name: ddeployer
