version: '3.8'

services:
  wordpress:
    image: dunglas/frankenphp:php8.3
    container_name: {{CONTAINER_NAME}}
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: {{DB_NAME}}
      WORDPRESS_DB_USER: {{DB_USER}}
      WORDPRESS_DB_PASSWORD: {{DB_PASSWORD}}
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: false
    volumes:
      - ./wordpress:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{CONTAINER_NAME}}.rule={{TRAEFIK_RULE}}"
      - "traefik.http.routers.{{CONTAINER_NAME}}.entrypoints={{ENTRYPOINTS}}"
      - "traefik.http.services.{{CONTAINER_NAME}}.loadbalancer.server.port=80"
      {{SSL_LABELS}}
    networks:
      - default

  db:
    image: mariadb:10.11
    container_name: {{CONTAINER_NAME}}-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: {{DB_PASSWORD}}
      MYSQL_DATABASE: {{DB_NAME}}
      MYSQL_USER: {{DB_USER}}
      MYSQL_PASSWORD: {{DB_PASSWORD}}
    volumes:
      - db_data:/var/lib/mysql
      - ./config/mysql.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - default

  redis:
    image: redis:7-alpine
    container_name: {{CONTAINER_NAME}}-redis
    restart: unless-stopped
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - default

volumes:
  db_data:
  redis_data:

networks:
  default:
    external:
      name: ddeployer
